version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - api-init:/docker-entrypoint-initdb.d:ro

  api:
    build: .
    ports:
      - "8989:8080"
    environment:
      DB_DSN: root:secret@tcp(db:3306)/bookstore
    volumes:
      - api-init:/init-export
    command: >
      sh -c "cp /app/init.sql /init-export/init.sql && ./server"

volumes:
  db-data:
  api-init:
