services:
  git:
    image: alpine
    volumes:
      - shared-code:/repo
    command: >
      sh -c "apk add --no-cache git && git clone --depth=1 https://github.com/andre-the-giant/go-bookstore-api.git /repo"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - shared-code:/docker-entrypoint-initdb.d:ro
    depends_on:
      - git

  api:
    image: golang:1.24
    working_dir: /repo
    command: sh -c "go mod tidy && go build -o server . && ./server"
    volumes:
      - shared-code:/repo
    ports:
      - "8989:8080"
    environment:
      DB_DSN: root:secret@tcp(db:3306)/bookstore
    depends_on:
      - db

volumes:
  db-data:
  shared-code:
