version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: .
    depends_on:
      - db
    environment:
      DB_DSN: root:secret@tcp(db:3306)/bookstore
    ports:
      - "8080:8080"

volumes:
  db-data:
